mmc: sdhci: fix two compile errors
| CC drivers/mmc/host/sdhci.o
| drivers/mmc/host/sdhci.c: In function 'sdhci_execute_tuning':
| drivers/mmc/host/sdhci.c:1990:4: error: implicit declaration of function 'sdhci_do_reset' [-Werror=implicit-function-declaration]
| sdhci_do_reset(host, SDHCI_RESET_CMD);
| ^
| drivers/mmc/host/sdhci.c:2006:7: error: 'struct mmc_command' has no member named 'busy_timeout'
| cmd.busy_timeout = 50;
|        ^

In function sdhci_execute_tuning, replace sdhci_do_reset
with sdhci_reset, replace busy_timeout with cmd_timeout_ms.

Commit a629a90ba0 adds eMMC DDR mode support for t2080qds and
modified some data structures and function name. Later
commit a2080cc280 just backport upstream commit 61e53bd004
without aligning the current source tree thus cause
these build errors. Fix them.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>