ASoC: SOF: trace: fix linker error in i386 mode
64-bit division or modulo needs to rely on do_div, cannot use / or %
in 32-bit mode

Fixes linker error

ERROR: "__moddi3" [sound/soc/sof/snd-sof.ko] undefined!
scripts/Makefile.modpost:92: recipe for target '__modpost' failed

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>