include/linux/property.h: fix build issues with gcc-4.4.4
gcc-4.4.4 has problems with initialization of anonymous unions:

drivers/mfd/intel-lpss-acpi.c:30: error: unknown field 'value' specified in initializer

work around this by crafting the initializers in a manner which the
compiler can handle.

Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit d76eebfa175e86383324ad2bbaf472866950398b)
Signed-off-by: Voon, Weifeng <weifeng.voon@intel.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>